# Generated by Django 2.2.7 on 2019-12-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300, verbose_name='Текст цитаты')),
                ('author', models.CharField(max_length=20, verbose_name='Автор')),
                ('email', models.EmailField(max_length=254, verbose_name='email автора')),
                ('status', models.CharField(choices=[('new', 'новая'), ('checked', 'проверена')], max_length=10, verbose_name='Статус')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
        ),
    ]
