# Generated by Django 2.2.7 on 2019-12-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('new', 'новая'), ('checked', 'проверена')], default='', max_length=10, verbose_name='Статус'),
        ),
    ]
